

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;  
import java.util.Calendar;
import java.util.Date; 
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jais
 */
public class Purchase extends javax.swing.JFrame {

    /**
     * Creates new form PurchasePage
     */
    public int id=0;
    public Purchase() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pid = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gstselect = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        closed = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        netamt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        item = new javax.swing.JComboBox<>();
        total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        item_name = new javax.swing.JTextField();
        preturn = new javax.swing.JButton();
        qty = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gst = new javax.swing.JTextField();
        vendor = new javax.swing.JComboBox<>();
        pdate = new com.toedter.calendar.JDateChooser();
        expdate = new com.toedter.calendar.JDateChooser();
        mfgdate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 150));
        setUndecorated(true);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pid.setForeground(new java.awt.Color(255, 255, 0));
        pid.setName("purchaseId"); // NOI18N
        jPanel1.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 60, 30));

        price.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        price.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                priceInputMethodTextChanged(evt);
            }
        });
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceKeyReleased(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Price");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 60, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Net Amount");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, 20));

        gstselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GST @ 5%", "GST @ 7%", "GST @ 10%", "GST @ 15%", "GST @ 18%" }));
        gstselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstselectActionPerformed(evt);
            }
        });
        jPanel1.add(gstselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 110, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Purchase Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 98, 30));

        closed.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        closed.setForeground(new java.awt.Color(255, 204, 255));
        closed.setText("X");
        closed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closedMouseClicked(evt);
            }
        });
        jPanel1.add(closed, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("OR");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        home.setBackground(new java.awt.Color(51, 51, 51));
        home.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 70, -1));

        save.setBackground(new java.awt.Color(51, 51, 51));
        save.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Item Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 80, 40));

        jLabel12.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" PURCHASE   ITEMS");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 200, 30));

        netamt.setEditable(false);
        netamt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(netamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Item Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("MFG Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Vendor Name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 90, 30));

        jPanel1.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 146, 170, 30));

        total.setEditable(false);
        total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Total Amount");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 90, 30));

        item_name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(item_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 180, 30));

        preturn.setBackground(new java.awt.Color(51, 51, 51));
        preturn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        preturn.setForeground(new java.awt.Color(255, 255, 255));
        preturn.setText("Purchase Return");
        preturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preturnMouseClicked(evt);
            }
        });
        jPanel1.add(preturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, -1, -1));

        qty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 100, 30));

        cancel.setBackground(new java.awt.Color(51, 51, 51));
        cancel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("EXP Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Purchase Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        gst.setEditable(false);
        gst.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        gst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstActionPerformed(evt);
            }
        });
        jPanel1.add(gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 100, 30));

        vendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorActionPerformed(evt);
            }
        });
        jPanel1.add(vendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 180, 30));

        pdate.setDateFormatString("yyyy/MM/dd");
        pdate.setEnabled(false);
        jPanel1.add(pdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 150, 30));

        expdate.setDateFormatString("yyyy/MM/dd");
        expdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                expdateFocusLost(evt);
            }
        });
        expdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                expdateMouseExited(evt);
            }
        });
        jPanel1.add(expdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 150, 30));

        mfgdate.setDateFormatString("yyyy/MM/dd");
        mfgdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mfgdateFocusLost(evt);
            }
        });
        jPanel1.add(mfgdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 170, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("_");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, -10, 20, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Quantity");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 80, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\java\\netbeans\\MedicalShopManagement\\img\\back brown3d.png")); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closedMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closedMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        ShopHome s=new ShopHome();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        
        
        String nm;
         boolean flag=false;
         
        try{
               
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
             Statement s=con.createStatement();
             
             String stckquery="select * from stock";
             ResultSet rs=s.executeQuery(stckquery);
             
             SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd",Locale.ENGLISH);
        
             Date mfgdt=mfgdate.getDate();
             Date expdt=expdate.getDate();
                
             long diffmil=(expdt.getTime() - mfgdt.getTime());
            long diff=TimeUnit.DAYS.convert(diffmil, TimeUnit.MILLISECONDS);
     
            if(diff<=0)
            {
                JOptionPane.showMessageDialog(null, "Product has already been Expired...");
                mfgdate.setDate(null);
                expdate.setDate(null);
                
            }   else
            {
             PreparedStatement st=con.prepareStatement("insert into purchase(pid,vendor,item,quantity,price,date)"+ "values(?,?,?,?,?,?) ");    
             st.setInt(1, id);
             st.setString(2, (String) vendor.getSelectedItem());
             if((item_name.getText().trim()).isEmpty()){
                nm=item.getSelectedItem().toString();
            }else{
                nm=item_name.getText();
           }
            
            st.setString(3, nm);
            st.setInt(4, Integer.parseInt(qty.getText()));
            st.setFloat(5,Float.parseFloat(price.getText()));
            SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy/MM/dd");
            String adddate=dateFormat.format(pdate.getDate());
            st.setString(6, adddate);
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Inserted successfully...");
           
            
            // Stock maintenance
           float pr=Float.parseFloat(price.getText());
            while(rs.next())    
            {
               if(nm.equalsIgnoreCase(rs.getString("itemname"))){
                int quant=rs.getInt("quantity");
                
                quant=quant + Integer.parseInt(qty.getText());
                
              PreparedStatement stmt=con.prepareStatement("UPDATE stock SET itemname=?,quantity=?,price=? WHERE itemname=? ");
              stmt.setString(4, nm);
              stmt.setString(1,nm);
              stmt.setString(2,String.valueOf(quant));
              stmt.setString(3,price.getText());
              
              stmt.executeUpdate();
            flag=false;
                JOptionPane.showMessageDialog(null, "Stock updated successfully...");
                break;
            }
            else{
                 flag=true;
                
            }
            }
            if(flag)
            {
                 PreparedStatement stmt=con.prepareStatement("insert into stock(itemname,quantity,price)"+ "values(?,?,?) ");
                stmt.setString(1, nm);
                stmt.setString(2,qty.getText());
                stmt.setString(3,price.getText() );
                stmt.executeUpdate();
                 JOptionPane.showMessageDialog(null, "Stock updated successfully...");
            }
                      
            }       // date else ending
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error in date or connection :: "+e);
        }
             
            pid.setText("");
            vendor.setSelectedIndex(0);
            item.setSelectedIndex(0);
            item_name.setText("");
            qty.setText("");
            price.setText("");
            mfgdate.setDate(null);
            expdate.setDate(null);
            total.setText("");
            pdate.setDate(null);
            netamt.setText("");
            gst.setText("");
            gstselect.setSelectedIndex(0);
    }//GEN-LAST:event_saveActionPerformed

    private void priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyReleased
        int quantity=Integer.parseInt(qty.getText());
        float itemprice=Float.parseFloat(price.getText());
        float tot=(quantity*itemprice);
        total.setText(String.valueOf(tot));
        netamt.setText(String.valueOf(tot));
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        Date today=new Date();
        sdf.format(today);
        pdate.setDate(today);
    }//GEN-LAST:event_priceKeyReleased

    private void priceInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_priceInputMethodTextChanged

    }//GEN-LAST:event_priceInputMethodTextChanged

    private void gstselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstselectActionPerformed
        int quantity=Integer.parseInt(qty.getText());
        float itemprice=Float.parseFloat(price.getText());
        float tot=0;
        float gstvalue=0;
        float netamount=0;
        tot=quantity*itemprice;
        int gstindex= gstselect.getSelectedIndex();
        if(gstindex==0){
            gstvalue=(tot*5)/100;
        }else if(gstindex==1){
            gstvalue=(tot*7)/100;
        } else if(gstindex==2){
            gstvalue=(tot*10)/100;
        } else if(gstindex==3){
            gstvalue=(tot*15)/100;
        } else if(gstindex==4){
            gstvalue=(tot*18)/100;
        }
        gst.setText(String.valueOf(gstvalue));
        netamount=tot+gstvalue;
        netamt.setText(String.valueOf(netamount));
    }//GEN-LAST:event_gstselectActionPerformed

    private void vendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendorActionPerformed

    private void preturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preturnMouseClicked
        PurchaseReturn pr=new PurchaseReturn();
        pr.setVisible(true);
        pr.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_preturnMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        ShopHome s=new ShopHome();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      //  int j=0;
        try {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
            Statement s=con.createStatement();
            ResultSet res,r;
        String qry="select itemname from stock GROUP BY itemname";
       String query="select * from purchase";
       String vquery="select name from vendor GROUP BY name";
       
       res=s.executeQuery(query);
       while(res.next()){
            id=res.getInt("pid");
            //System.out.println(id);
             }
       id++;
       pid.setText(String.valueOf(id));
      // int i=0;
 //      int j=item.getItemCount();
        res=s.executeQuery(qry);
       while(res.next()){
          
           item.addItem(res.getString("itemname"));
       }
       r=s.executeQuery(vquery);
       while(r.next())
       {/*
             if(!(r.getString("name").equals(vendor.getItemAt(j)))){
                 vendor.addItem(r.getString("name"));
                 j++;
             
             }*/
           vendor.addItem(r.getString("name"));
         }
       
       
       
      
      
        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"connection failed...:"+e);
        }
 
       
    }//GEN-LAST:event_formWindowActivated

    private void gstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gstActionPerformed

    private void mfgdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mfgdateFocusLost
        // TODO add your handling code here:
          
    }//GEN-LAST:event_mfgdateFocusLost

    private void expdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expdateMouseExited
        // TODO add your handling code here:
          
   
            
    }//GEN-LAST:event_expdateMouseExited

    private void expdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expdateFocusLost
        // TODO add your handling code here:
          
    }//GEN-LAST:event_expdateFocusLost

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
            try {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
            Statement s=con.createStatement();
            ResultSet res,r;
        String qry="select itemname from stock GROUP BY itemname";
       String query="select * from purchase";
       String vquery="select name from vendor GROUP BY name";
       
       res=s.executeQuery(query);
       while(res.next()){
            id=res.getInt("pid");
             }
       id++;
       pid.setText(String.valueOf(id));
    
        res=s.executeQuery(qry);
       while(res.next()){
           
           item.addItem(res.getString("itemname"));
       }
       r=s.executeQuery(vquery);
       while(r.next())
       {
           vendor.addItem(r.getString("name"));
         }
  }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"connection failed...:"+e);
        }
 
    }//GEN-LAST:event_formWindowStateChanged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
                // TODO add your handling code here:
                this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel closed;
    private com.toedter.calendar.JDateChooser expdate;
    private javax.swing.JTextField gst;
    private javax.swing.JComboBox<String> gstselect;
    private javax.swing.JButton home;
    private javax.swing.JComboBox<String> item;
    private javax.swing.JTextField item_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser mfgdate;
    private javax.swing.JTextField netamt;
    private com.toedter.calendar.JDateChooser pdate;
    private javax.swing.JLabel pid;
    private javax.swing.JButton preturn;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qty;
    private javax.swing.JButton save;
    private javax.swing.JTextField total;
    private javax.swing.JComboBox<String> vendor;
    // End of variables declaration//GEN-END:variables
}
