
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jais
 */
public class Sales extends javax.swing.JFrame {

    /**
     * Creates new form Sales
     */
    public int id=0;
    public Sales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        sreturn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gst = new javax.swing.JComboBox<>();
        itemnm = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        sid = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        netamt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        custnm = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        gstprice = new javax.swing.JTextField();
        sdate = new com.toedter.calendar.JDateChooser();
        closed = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mobile_val = new javax.swing.JLabel();
        customer_val = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        setForeground(new java.awt.Color(255, 204, 255));
        setLocation(250,150);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 204));
        jButton2.setText("Home");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 80, -1));

        sreturn.setBackground(new java.awt.Color(51, 51, 51));
        sreturn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        sreturn.setForeground(new java.awt.Color(255, 204, 204));
        sreturn.setText("Sale Return");
        sreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sreturnMouseClicked(evt);
            }
        });
        getContentPane().add(sreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Net Amount");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 100, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Sale Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 60, -1));

        gst.setBackground(new java.awt.Color(204, 204, 255));
        gst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gst.setForeground(new java.awt.Color(255, 255, 51));
        gst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GST@5%", "GST@7%", "GST@10%", "GST@15%", "GST@18%" }));
        gst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstActionPerformed(evt);
            }
        });
        getContentPane().add(gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 110, -1));

        itemnm.setBackground(new java.awt.Color(204, 204, 255));
        itemnm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        itemnm.setForeground(new java.awt.Color(255, 255, 255));
        itemnm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item Name..." }));
        itemnm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemnmItemStateChanged(evt);
            }
        });
        itemnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnmActionPerformed(evt);
            }
        });
        getContentPane().add(itemnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 60, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Total Amout");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 100, 40));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 204, 204));
        jButton5.setText("Cancel");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 80, -1));

        savebtn.setBackground(new java.awt.Color(51, 51, 51));
        savebtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 204, 204));
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 70, -1));

        total.setEditable(false);
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 60, 30));

        sid.setEditable(false);
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 50, 30));

        qty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qtyFocusLost(evt);
            }
        });
        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 60, 30));

        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceKeyReleased(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 60, 30));

        netamt.setEditable(false);
        getContentPane().add(netamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 70, 30));

        jLabel8.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("  SALES ITEM");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 2, true));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 140, 30));

        custnm.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        custnm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                custnmKeyPressed(evt);
            }
        });
        getContentPane().add(custnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 51, 130, 30));

        mob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mobKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobKeyReleased(evt);
            }
        });
        getContentPane().add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Mobile");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 50, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Customer Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 80, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Date");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 50, 20));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 130, 30));

        gstprice.setEditable(false);
        gstprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstpriceActionPerformed(evt);
            }
        });
        getContentPane().add(gstprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 70, 30));

        sdate.setEnabled(false);
        getContentPane().add(sdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 130, 30));

        closed.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        closed.setForeground(new java.awt.Color(255, 204, 255));
        closed.setText("X");
        closed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closedMouseClicked(evt);
            }
        });
        getContentPane().add(closed, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 204));
        jLabel5.setText("_");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 20, 30));

        mobile_val.setName("mobile_validate"); // NOI18N
        getContentPane().add(mobile_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 130, 10));

        customer_val.setName("customer_validate"); // NOI18N
        getContentPane().add(customer_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 130, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\java\\netbeans\\MedicalShopManagement\\img\\26-dw.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closedMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closedMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        ShopHome s=new ShopHome();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        ShopHome s=new ShopHome();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void sreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sreturnMouseClicked
        SalesReturn sr=new SalesReturn();
        sr.setVisible(true);
        sr.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_sreturnMouseClicked

    private void priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyReleased
   
       
    }//GEN-LAST:event_priceKeyReleased

    private void gstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstActionPerformed
        int quantity=Integer.parseInt(qty.getText());
        float itemprice=Float.parseFloat(price.getText());
        float tot=0;
        float gstvalue=0;
        float netamount=0;
        tot=quantity*itemprice;
        int gstindex= gst.getSelectedIndex();
        if(gstindex==0){
            gstvalue=(tot*5)/100;
        }else if(gstindex==1){
            gstvalue=(tot*7)/100;
        } else if(gstindex==2){
            gstvalue=(tot*10)/100;
        } else if(gstindex==3){
            gstvalue=(tot*15)/100;
        } else if(gstindex==4){
            gstvalue=(tot*18)/100;
        }
        gstprice.setText(String.valueOf(gstvalue));
        netamount=tot+gstvalue;
        netamt.setText(String.valueOf(netamount));
    }//GEN-LAST:event_gstActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
      /*      
        try{
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd",Locale.ENGLISH);
        
             Date saledt=sdate.getDate();
          //   Date today=(Date)Calendar.getInstance(Locale.ENGLISH);
                
             long diffmil=(saledt.getTime());
            long diff=TimeUnit.DAYS.convert(diffmil, TimeUnit.MILLISECONDS);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, ""+e);
        }
        */
        try {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
             Statement s=con.createStatement();
             PreparedStatement st=con.prepareStatement("insert into sale(sid,item,quantity,price,customer,address,mobile,date)"+ "values(?,?,?,?,?,?,?,?) ");    
            st.setInt(1, id);
            st.setString(2, (String) itemnm.getSelectedItem());
            st.setInt(3, Integer.parseInt(qty.getText()));
            st.setFloat(4,Float.parseFloat(price.getText()));
            st.setString(5, custnm.getText());
            st.setString(6, address.getText());
            st.setString(7, mob.getText());
            SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
            String adddate=dateFormat.format(sdate.getDate());
            st.setString(8, adddate);
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Inserted successfully...");
            // Stock maintenance
            String stckquery="Select * from stock";
            ResultSet rs;
            rs=s.executeQuery(stckquery);
            while(rs.next()){
            if((itemnm.getSelectedItem().toString()).equalsIgnoreCase(rs.getString("itemname"))){
                int quant=rs.getInt("quantity");
                quant=quant-Integer.parseInt(qty.getText());
               PreparedStatement stmt=con.prepareStatement("UPDATE stock SET itemname=?,quantity=?,price=? WHERE itemname=? ");
               stmt.setString(4, itemnm.getSelectedItem().toString());
               stmt.setString(1, itemnm.getSelectedItem().toString());
               stmt.setInt(2, quant);
               stmt.setFloat(3,Float.parseFloat(price.getText()));
               stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Stock Updated...");
               break;
            }
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, ""+e);
        }
             sid.setText("");
            itemnm.setSelectedIndex(0);
            qty.setText("");
            price.setText("");
            total.setText("");
            custnm.setText("");
            address.setText("");
            mob.setText("");
            sdate.setDate(null);
            gstprice.setText("");
            netamt.setText("");
            gst.setSelectedIndex(0);
    }//GEN-LAST:event_savebtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      // int i=0;
        try {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
            Statement s=con.createStatement();
            ResultSet res;
            
            String query="select * from sale";
            res=s.executeQuery(query);
            
       while(res.next()){
            id=res.getInt("sid");
                    
           }//end of outer while
       id++;
      sid.setText(String.valueOf(id));
      String qry="select DISTINCT itemname from stock GROUP BY itemname";
            res=s.executeQuery(qry);
       while(res.next()){
            itemnm.addItem(res.getString("itemname"));
           
            }
      
        }  catch (Exception e) {
            JOptionPane.showMessageDialog(null, ""+e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void gstpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gstpriceActionPerformed

    private void itemnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnmActionPerformed
        try {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
            Statement s=con.createStatement();
            ResultSet res;
        
       String query="select * from stock";
       res=s.executeQuery(query);
       while(res.next()){
        if((itemnm.getSelectedItem().toString()).equals(res.getString("itemname"))){
          price.setText(String.valueOf(res.getFloat("price")));
          con.close();
            break;
            }
        }  
        }catch (Exception e) {
            
        }
    }//GEN-LAST:event_itemnmActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_qtyKeyPressed

    private void qtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_qtyFocusLost

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_qtyKeyTyped

    private void mobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_mobKeyReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void custnmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custnmKeyPressed
        
        char c=evt.getKeyChar();
        if(Character.isDigit(c))
        {
            custnm.setEditable(false);
            customer_val.setVisible(true);
            customer_val.setText("Invalid Character typed...");
        }
        else{
            custnm.setEditable(true);
            customer_val.setVisible(false);
            
                    
        }
    }//GEN-LAST:event_custnmKeyPressed

    private void mobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        int len=mob.getText().length();
        if(!Character.isDigit(c)||len>=10 )
        {
            mob.setEditable(false);
            
           //evt.consume();
            mobile_val.setVisible(true);
            mobile_val.setText("Invalid Character typed...");
        }
        else{
            mob.setEditable(true);
            mobile_val.setVisible(false);
            
                    
        }
    }//GEN-LAST:event_mobKeyPressed

    private void itemnmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemnmItemStateChanged
        
    }//GEN-LAST:event_itemnmItemStateChanged

    private void qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyReleased
        // TODO add your handling code here:
        int quant=Integer.parseInt(qty.getText());
        float pr=quant*(Float.parseFloat(price.getText()));
        total.setText(String.valueOf(pr));
        netamt.setText(String.valueOf(pr));
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        Date today=new Date();
        sdf.format(today);
        sdate.setDate(today);
    }//GEN-LAST:event_qtyKeyReleased
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel closed;
    private javax.swing.JTextField custnm;
    private javax.swing.JLabel customer_val;
    private javax.swing.JComboBox<String> gst;
    private javax.swing.JTextField gstprice;
    private javax.swing.JComboBox<String> itemnm;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mob;
    private javax.swing.JLabel mobile_val;
    private javax.swing.JTextField netamt;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qty;
    private javax.swing.JButton savebtn;
    private com.toedter.calendar.JDateChooser sdate;
    private javax.swing.JTextField sid;
    private javax.swing.JButton sreturn;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
