
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jais
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form Stock
     */
    public Stock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        additem = new javax.swing.JLabel();
        viewitem = new javax.swing.JLabel();
        deleteitem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        closed = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelname = new javax.swing.JLabel();
        itmnm = new javax.swing.JTextField();
        labelqty = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        labelprice = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 150));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("         Delete Item");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("  Add Item");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 60, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Edit/View Item");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 90, 20));

        additem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_add-item-icon.png"))); // NOI18N
        additem.setText("\n");
        additem.setToolTipText("Add Item in the Stock");
        additem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                additemMouseClicked(evt);
            }
        });
        getContentPane().add(additem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 130));

        viewitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_shopping-23-512.png"))); // NOI18N
        viewitem.setToolTipText("Search/View/Edit ");
        viewitem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewitemMouseClicked(evt);
            }
        });
        viewitem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                viewitemKeyPressed(evt);
            }
        });
        getContentPane().add(viewitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 100, 110));

        deleteitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_1delete_icon.png"))); // NOI18N
        deleteitem.setToolTipText("Delete Item from Stock");
        deleteitem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteitemMouseClicked(evt);
            }
        });
        getContentPane().add(deleteitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 100, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\java\\netbeans\\MedicalShopManagement\\src\\imgs\\apple1.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 400));

        closed.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        closed.setForeground(new java.awt.Color(255, 204, 255));
        closed.setText("X");
        closed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closedMouseClicked(evt);
            }
        });
        getContentPane().add(closed, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 20, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 255));
        jLabel3.setText("Stock Opertion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 140, 30));

        labelname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelname.setForeground(new java.awt.Color(255, 204, 255));
        labelname.setText("Item name");
        getContentPane().add(labelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 90, 20));

        itmnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmnmActionPerformed(evt);
            }
        });
        getContentPane().add(itmnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 100, 30));

        labelqty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelqty.setForeground(new java.awt.Color(255, 204, 255));
        labelqty.setText("Quantity");
        getContentPane().add(labelqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 60, 20));
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 100, 30));

        labelprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelprice.setForeground(new java.awt.Color(255, 204, 255));
        labelprice.setText("Price");
        getContentPane().add(labelprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 90, 20));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 100, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 80, 40));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 204));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 90, 40));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 204));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("_");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 20, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\java\\netbeans\\MedicalShopManagement\\src\\imgs\\back brown3d.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closedMouseClicked
        ShopHome sh=new ShopHome();
        sh.setVisible(true);
        sh.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_closedMouseClicked

    private void itmnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmnmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int log=0;
          try {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
             Statement s=con.createStatement();
            String query="select * from stock";
            ResultSet rs=s.executeQuery(query);
            while(rs.next()){
                if(rs.getString("itemname").equalsIgnoreCase(itmnm.getText())){
                itmnm.setText(rs.getString("itemname"));
                qty.setText(String.valueOf(rs.getInt("quantity")));
                price.setText(String.valueOf(rs.getFloat("price")));
                log++;
                break;
                }
                else{
                    log=0;
                    
                }
            }
            if(log==0){
                  PreparedStatement ps=con.prepareStatement("insert into stock(itemname,quantity,price)"+"values(?,?,?)");
                ps.setString(1,itmnm.getText());
                ps.setInt(2, Integer.parseInt(qty.getText()));
                ps.setFloat(3,Float.parseFloat(price.getText()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record Inserted");
             }
            else{
              JOptionPane.showMessageDialog(null, "Item Exists...","",JOptionPane.ERROR_MESSAGE);
               
            }
           
                    }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e,"",JOptionPane.ERROR_MESSAGE);
        }
           itmnm.setText("");
            qty.setText("");
             price.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteitemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteitemMouseClicked
        labelqty.setVisible(false);
        labelprice.setVisible(false);
        qty.setVisible(false);
        price.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(true);
        jButton3.setVisible(false);
    }//GEN-LAST:event_deleteitemMouseClicked

    private void additemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_additemMouseClicked
        labelqty.setVisible(true);
        labelprice.setVisible(true);
        qty.setVisible(true);
        price.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
    }//GEN-LAST:event_additemMouseClicked

    private void viewitemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viewitemKeyPressed
       
    }//GEN-LAST:event_viewitemKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int log=0;
          try {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
             Statement s=con.createStatement();
            String query="select * from stock";
            String dquery="delete from stock where itemname= '"+ itmnm.getText()+"'";
            ResultSet rs=s.executeQuery(query);
            while(rs.next()){
                if(rs.getString("itemname").equalsIgnoreCase(itmnm.getText())){
                s.execute(dquery);
                log++;
                break;
                }
                else{
                    log=0;
                    
                }
            }
            if(log==0){
                
                JOptionPane.showMessageDialog(null, "Record Doesn't Exist","",JOptionPane.ERROR_MESSAGE);
             }
            else{
              JOptionPane.showMessageDialog(null, "Item Deleted ="+ itmnm.getText());
              }
                    }
        catch (Exception e) {
           // JOptionPane.showMessageDialog(null, "Please Enter Valid Purchase ID"+e,"",JOptionPane.ERROR_MESSAGE);
        }
          itmnm.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void viewitemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewitemMouseClicked
        labelqty.setVisible(true);
        labelprice.setVisible(true);
        qty.setVisible(true);
        price.setVisible(true);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(true);
    }//GEN-LAST:event_viewitemMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
          try {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
             Statement s=con.createStatement();
            String dquery="UPDATE stock SET itemname=?,quantity=?,price=? WHERE itemname=? ";
             PreparedStatement pst=con.prepareStatement(dquery);
          
          pst.setString(4,itmnm.getText());
          pst.setString(1,itmnm.getText());
          pst.setString(2,qty.getText());
          pst.setString(3,price.getText());
          pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "Record Updated...");
        }
        catch (Exception e) {
           JOptionPane.showMessageDialog(null, "ItemName doesnot exist...");
        }
         itmnm.setText("");
            qty.setText("");
             price.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel additem;
    private javax.swing.JLabel closed;
    private javax.swing.JLabel deleteitem;
    private javax.swing.JTextField itmnm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelname;
    private javax.swing.JLabel labelprice;
    private javax.swing.JLabel labelqty;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qty;
    private javax.swing.JLabel viewitem;
    // End of variables declaration//GEN-END:variables
}
