
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jais
 */
public class Vendor extends javax.swing.JFrame {

    /**
     * Creates new form Vendor
     */
    public Vendor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        closed = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        vmob = new javax.swing.JLabel();
        vadd = new javax.swing.JLabel();
        vgst = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        vname = new javax.swing.JTextField();
        gstnumber = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        mobileval = new javax.swing.JLabel();
        vnmval = new javax.swing.JLabel();
        gstval = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Add Vendor");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(225, 150));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closed.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        closed.setForeground(new java.awt.Color(255, 204, 255));
        closed.setText("X");
        closed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closedMouseClicked(evt);
            }
        });
        getContentPane().add(closed, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 20, 20));

        min.setFont(new java.awt.Font("Felix Titling", 1, 56)); // NOI18N
        min.setForeground(new java.awt.Color(255, 204, 255));
        min.setText("-");
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 20, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("Add Vendor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("Delete Vendor");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 90, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("View/Edit");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 80, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_user6.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_1delete_icon.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_view.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\java\\netbeans\\MedicalShopManagement\\img\\apple1.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        jlabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(255, 204, 255));
        jlabel4.setText("Name");
        getContentPane().add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 40, 20));

        vmob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vmob.setForeground(new java.awt.Color(255, 204, 255));
        vmob.setText("Mobile");
        getContentPane().add(vmob, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 50, 20));

        vadd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vadd.setForeground(new java.awt.Color(255, 204, 255));
        vadd.setText("Address");
        getContentPane().add(vadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 90, 20));

        vgst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vgst.setForeground(new java.awt.Color(255, 204, 255));
        vgst.setText("Gst Number");
        getContentPane().add(vgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 90, 20));

        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mobileKeyPressed(evt);
            }
        });
        getContentPane().add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 110, 30));

        vname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vnameKeyPressed(evt);
            }
        });
        getContentPane().add(vname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 110, 30));

        gstnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gstnumberKeyPressed(evt);
            }
        });
        getContentPane().add(gstnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 110, 30));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 140, 40));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 70, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 204));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 204));
        jButton3.setText("Update");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText("Vendor Operation");
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 2, true));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 170, -1));

        mobileval.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(mobileval, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 130, 20));

        vnmval.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(vnmval, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 110, 20));

        gstval.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(gstval, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 130, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\java\\netbeans\\MedicalShopManagement\\img\\back brown3d.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closedMouseClicked
        ShopHome sh=new ShopHome();
        sh.setVisible(true);
        sh.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_closedMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add vendor button
        int log=0;
          try {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
            Statement s=con.createStatement();
            String query="select * from vendor";
            ResultSet rs;
            rs=s.executeQuery(query);
            while(rs.next()){
                if((mobile.getText()).equals(rs.getString("mobile"))){
                    JOptionPane.showMessageDialog(null,"This Mobile number is already added");
                    mobile.setText("");
                    vname.setText("");
                   // jTextField3.setText("");
                    gstnumber.setText("");
                    jTextField5.setText("");
                    
                    break;
                }
                else{
                    log=0;
                            
                }
            }
            if(log==0)
            {
                PreparedStatement st=con.prepareStatement("insert into vendor(mobile,name,gstnumber,address)"+ "values(?,?,?,?)");
                    st.setString(1, mobile.getText());
                    st.setString(2, vname.getText());
//                    st.setString(3, jTextField3.getText());
                    st.setString(3, gstnumber.getText());
                    st.setString(4, jTextField5.getText());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Record Saved...");
            }
             else{
              JOptionPane.showMessageDialog(null, "Item Exists...","",JOptionPane.ERROR_MESSAGE);
               
            }
          }catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
          }
           jButton1.setVisible(true);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
         jlabel4.setVisible(true);
        vadd.setVisible(true);
//        vmail.setVisible(true);
        vgst.setVisible(true);
        vname.setVisible(true);
    //    jTextField3.setVisible(true);
        gstnumber.setVisible(true);
        jTextField5.setVisible(true);
        mobile.setText("");
        vname.setText("");
        gstnumber.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
         jButton1.setVisible(true);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
         jlabel4.setVisible(true);
        vadd.setVisible(true);
     //   vmail.setVisible(true);
        vgst.setVisible(true);
        vname.setVisible(true);
     //   jTextField3.setVisible(true);
        gstnumber.setVisible(true);
        jTextField5.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
//       Vendor v=new Vendor();
//        v.setVisible(true);
//        v.setLocationRelativeTo(null);
//        this.dispose();
        jButton1.setVisible(false);
        jButton2.setVisible(true);
        jButton3.setVisible(false);
        jlabel4.setVisible(false);
        vadd.setVisible(false);
//        vmail.setVisible(false);
        vgst.setVisible(false);
        vname.setVisible(false);
     //   jTextField3.setVisible(false);
        gstnumber.setVisible(false);
        jTextField5.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(true);
         jlabel4.setVisible(true);
        vadd.setVisible(true);
//        vmail.setVisible(true);
        vgst.setVisible(true);
        vname.setVisible(true);
 //       jTextField3.setVisible(true);
        gstnumber.setVisible(true);
        jTextField5.setVisible(true);
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int log=0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
            Statement s=con.createStatement();
            String query="select * from vendor";
           ResultSet rs=s.executeQuery(query);
            String dquery="delete from vendor where mobile='"+mobile.getText()+"'";
              while(rs.next()){
                if(rs.getString("mobile").equalsIgnoreCase(mobile.getText())){
                s.execute(dquery);
                log++;
                break;
                }
                else{
                    log=0;
                    
                }
            }
            if(log==0){
                
                JOptionPane.showMessageDialog(null, "Record Doesn't Exist Invalid Mobile","",JOptionPane.ERROR_MESSAGE);
             }
            else{
               
              JOptionPane.showMessageDialog(null, "Vendor Deleted ="+ mobile.getText());
              }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Mobile...","",JOptionPane.ERROR_MESSAGE);
        }
          jButton1.setVisible(false);
        jButton2.setVisible(true);
        jButton3.setVisible(false);
        jlabel4.setVisible(false);
        vadd.setVisible(false);
//        vmail.setVisible(false);
        vgst.setVisible(false);
        vname.setVisible(false);
       // jTextField3.setVisible(false);
        gstnumber.setVisible(false);
        jTextField5.setVisible(false);
        mobile.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        int log=0;   
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
            Statement s=con.createStatement();
            String q="select * from vendor";
            ResultSet rs=s.executeQuery(q);
            while(rs.next()){
                if((mobile.getText()).equals(rs.getString("mobile"))){
                  log=1;  
                  break;
                }
            }
            if (log==1){
            String uquery="UPDATE vendor SET mobile= ?, name = ?, gstnumber = ?, email = ?, address = ?";
            s.executeQuery(uquery);
              JOptionPane.showMessageDialog(null, "Updated Successfully...");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Mobile...","",JOptionPane.ERROR_MESSAGE);
        }
           jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(true);
         jlabel4.setVisible(true);
        vadd.setVisible(true);
//        vmail.setVisible(true);
        vgst.setVisible(true);
        vname.setVisible(true);
  //      jTextField3.setVisible(true);
        gstnumber.setVisible(true);
        jTextField5.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
          try {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/myshop","root","");
             Statement s=con.createStatement();
            String dquery="UPDATE vendor SET mobile=?,name=?,gstnumber=?,address=? WHERE mobile=? ";
             PreparedStatement pst=con.prepareStatement(dquery);
          
          pst.setString(5,mobile.getText());
          pst.setString(1,mobile.getText());
          pst.setString(2,vname.getText());
          pst.setString(3,gstnumber.getText());
          pst.setString(4,jTextField5.getText());
          pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "Record Updated...");
        }
        catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Vendor mobile :"+mobile.getText()+" doesnot exist...");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileKeyPressed
         char c=evt.getKeyChar();
         int len=mobile.getText().length();
        if(!Character.isDigit(c) || len>=10)
        {
            mobile.setEditable(false);
           
            mobileval.setVisible(true);
             mobileval.setText("Invalid Character typed...");
        }
        else{
            mobile.setEditable(true);
            mobileval.setVisible(false);
          
                    
        }
    }//GEN-LAST:event_mobileKeyPressed

    private void vnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vnameKeyPressed
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(!Character.isLetter(c))
        {
           vname.setEditable(false);
          
            vnmval.setVisible(true);
            vnmval.setText("Invalid Character typed...");
        }
        else{
            vname.setEditable(true);
            vnmval.setVisible(false);
           
                    
        }
    }//GEN-LAST:event_vnameKeyPressed

    private void gstnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gstnumberKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
         int len=gstnumber.getText().length();
        if((!Character.isDigit(c)||!Character.isLetter(c))&&len>=15)
        {
            gstnumber.setEditable(false);
           //evt.consume();
            gstval.setVisible(true);
            gstval.setText("Invalid Character typed...");
        }
        else{
            gstnumber.setEditable(true);
            gstval.setVisible(false);
           
                    
        }
    }//GEN-LAST:event_gstnumberKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closed;
    private javax.swing.JTextField gstnumber;
    private javax.swing.JLabel gstval;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel min;
    private javax.swing.JTextField mobile;
    private javax.swing.JLabel mobileval;
    private javax.swing.JLabel vadd;
    private javax.swing.JLabel vgst;
    private javax.swing.JLabel vmob;
    private javax.swing.JTextField vname;
    private javax.swing.JLabel vnmval;
    // End of variables declaration//GEN-END:variables
}
